# Generated by Django 4.1.4 on 2022-12-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="content", field=models.TextField(max_length=255),
        ),
    ]
