# Generated by Django 4.1.4 on 2022-12-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=100)),
                ("comments", models.CharField(max_length=100)),
                ("phone", models.IntegerField(null=True)),
            ],
        ),
    ]
