# Generated by Django 4.1.4 on 2022-12-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_contact"),
    ]

    operations = [
        migrations.RenameField(model_name="contact", old_name="name", new_name="Name",),
    ]
