# Generated by Django 4.1.4 on 2022-12-08 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_name_contact_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog", options={"ordering": ["-created_on"]},
        ),
        migrations.RenameField(model_name="contact", old_name="Name", new_name="name",),
        migrations.AddField(
            model_name="blog",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
