# Generated by Django 4.1.4 on 2022-12-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blog_slug_alter_blog_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
