# Generated by Django 4.1.4 on 2022-12-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blog_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="slug",),
        migrations.AddField(
            model_name="blog",
            name="feature_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
