# Generated by Django 4.1.4 on 2022-12-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_remove_blog_slug_blog_feature_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="feature_image",),
    ]
